#!/bin/sh -ex

NAME=roundup
USER=roundup
ADMIN_PASS=turnkey
DB_PASS=$(mcookie)

RT_TRACKER=/var/lib/roundup/tracker
RT_TEMPLATE=classic
RT_BACKEND=mysql

adduser --disabled-login --gecos 'roundup' $USER

su - $USER -c "pip install 'roundup==1.6.0' --user"

#  set home access perms
RT_LOCAL=/home/$USER/.local
chmod -R 0775 ${RT_LOCAL}
chmod -R 0774 ${RT_LOCAL}/share

# allow Apache access to docs - requires search perms (x on directory)
# for full path
DOCS=$RT_LOCAL/share/doc/roundup/html
SUB_DIRS="_images _sources _static"
for dir in $SUB_DIRS; do
    chmod o+x $DOCS/$dir
done
dir=$DOCS
while [ "$dir" != "$(dirname $RT_LOCAL)" ]; do
    chmod o+x $dir
    dir=$(dirname $dir)
done

#  add symlinks
LOCAL=/usr/local
TARGETS="/bin/roundup-admin /bin/roundup-gettext /bin/roundup-mailgw /share/roundup"
for target in $TARGETS; do
    ln -sf ${RT_LOCAL}${target} ${LOCAL}${target}
done
TARGET=/lib/python2.7
ln -sf ${RT_LOCAL}${TARGET}/site-packages/roundup ${LOCAL}${TARGET}/dist-packages/roundup
ln -sf ${RT_LOCAL}${TARGET}/site-packages/roundup-1.5.1.dist-info ${LOCAL}${TARGET}/dist-packages/roundup-1.5.1.dist-info


# workaround rowsize issue for mariadb 10.1
patch ${RT_LOCAL}/lib/python2.7/site-packages/roundup/backends/back_mysql.py /usr/local/src/back_mysql.patch

# convenience symlinks
ln -s $RT_TRACKER /var/www/webroot
ln -s /etc/roundup /var/www/config
ln -s /usr/share/doc/roundup /var/www/docs


# innodb workaround (Incorrect information in file: './roundup/schema.frm'")
service mysql start
service mysql stop
rm /var/lib/mysql/ib*

# update MariaDB defaults to work around MariaDB10.1 bug
MYCNF=/etc/mysql/mariadb.conf.d/99-turnkey-redmine-workaround.cnf
cat > $MYCNF <<EOF
[mysqld]
default_tmp_storage_engine = InnoDB
innodb_file_format = Barracuda
innodb_file_format_max = Barracuda
innodb_large_prefix = 1
EOF

a2enmod python

# start mysql server
service mysql start

# create roundup and user and grant privs to yet to be created db
mysql --user=root --password=$MYSQL_PASS --batch --execute "\
GRANT ALL PRIVILEGES ON $NAME.* TO $NAME@localhost IDENTIFIED BY '$DB_PASS'; \
FLUSH PRIVILEGES;"

mkdir -p $RT_TRACKER
mkdir /etc/roundup
chown -R roundup:roundup $RT_TRACKER
OPTIONS="admin_email=admin,dispatcher_email=admin,tracker_web=/,mail_domain=example.com,mail_host=localhost,rdbms_password=$DB_PASS"
su - $USER -c "roundup-admin -i $RT_TRACKER install $RT_TEMPLATE $RT_BACKEND $OPTIONS
roundup-admin -i $RT_TRACKER initialise $ADMIN_PASS"
echo "tracker = $RT_TRACKER" >> /etc/roundup/roundup-server.ini
chown -R www-data:www-data $RT_TRACKER/db

# move tracker configuration to etc
mv $RT_TRACKER/config.ini /etc/roundup/tracker-config.ini
ln -s /etc/roundup/tracker-config.ini $RT_TRACKER/config.ini

# disable registration confirmation via email (requires mail server)
OPTION=email_registration_confirmation
sed -i "s|^$OPTION = yes|$OPTION = no|" /etc/roundup/tracker-config.ini

# create link to local documentation
sed -i "s;Roundup docs</a>;Roundup docs</a>\n    (<a href=\"/docs\" i18n:translate=\"\">local</a>);" $RT_TRACKER/html/page.html

# don't display turnkey-credit in popups
for file in *.help*.html _generic.calendar.html; do
    sed -i "s|</head>|<style type='text/css'> #turnkey-credit { display: none; }</style>\n  </head>|" $RT_TRACKER/html/$file
done

# apache configuration
a2dissite 000-default
a2ensite roundup
rm -rf /var/www/html

# remove empty folder created for multiple instances
rm -rf /var/lib/roundup/trackers

# stop mysql server
service mysql stop

