#!/bin/bash -e
# regenerate roundup tracker secrets and mysql password

. /etc/default/inithooks

CONF=/etc/roundup/tracker-config.ini

rand() { head -c 32 /dev/urandom | base64; }

# regen tracker and jwt secrets
sed -i "\|^jwt_secret =| s|=.*|= $(rand)|" $CONF
sed -i "\|^secret_key =| s|=.*|= $(rand)|" $CONF

# regen roundup mysql user password
PASSWORD=$(mcookie)
sed -i "\|^password =| s|=.*|= $PASSWORD|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=roundup --pass="$PASSWORD"
