#!/bin/bash -e
# set roundup admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/roundup.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

